import Head from "next/head"
import { AppContextProvider } from "/src/components/AppContext"
import Header from "/src/components/Header"

const Layout = (props) => {
  const { children, ...otherProps } = props

  return (
    <AppContextProvider>
      <div className="relative min-h-screen" {...otherProps}>
        <Head>
          <title>{props.pagetitle} | Tableau des finances</title>
          <meta
            name="viewport"
            content="initial-scale=1.0, width=device-width"
          />
          <meta
            name="description"
            content="Generated by create next app and dev"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header pagetitle={props.pagetitle} />
        <main className="w-4/6 p-8 border-2 rounded-lg shadow-xl mx-auto">
          {children}
        </main>
      </div>
    </AppContextProvider>
  )
}

export default Layout
