import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import Header from "./Header";

const Layout = (props) => {
  const { children, ...otherProps } = props;
  const router = useRouter();

  const TitleRender = (router) => {
    const [title, setTitle] = useState(null);

    useEffect(() => {
      const actualPage =
        router.pathname === "/"
          ? "Journal"
          : router.pathname.substring(1).charAt(0).toUpperCase() +
            router.pathname.slice(2).replace(/(-)/g, " ");
      setTitle(actualPage);
    }, [router.pathname]);

    return title;
  };

  return (
    <div className="relative min-h-screen" {...otherProps}>
      <Head>
        <title>{TitleRender(router)} | Tableau des finances</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title={TitleRender(router)} />
      <main className="w-4/6 p-8 border-2 mx-auto">{children}</main>
    </div>
  );
};

export default Layout;
