import Head from "next/head";
import { useRouter } from "next/router";
import Header from "./Header";
import Footer from "./Footer";

const Page = (props) => {
  const { children, ...otherProps } = props;
  const router = useRouter();

  const TitleRender = (homeTitle) => {
    const render =
      router.pathname === "/"
        ? homeTitle
        : router.pathname.substring(1).charAt(0).toUpperCase() +
          router.pathname.slice(2).replaceAll("-", " ");

    return render;
  };

  return (
    <div {...otherProps}>
      <Head>
        <title>{TitleRender("Carnet")} | Tableau des finances</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title={TitleRender("Carnet")} />
      <main>{children}</main>
      <Footer />
    </div>
  );
};

export default Page;
